// not real recipes id (real ids on spoonacular api)
[
  {
    cuisine: "african",
    results: [
      {
        id: 1,
        title: "African Chicken Peanut Stew",
        image: "https://spoonacular.com/recipeImages/716268-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 2,
        title: "African Bean Soup",
        image: "https://spoonacular.com/recipeImages/632003-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 3,
        title: "How to Make Party Jollof Rice",
        image: "https://spoonacular.com/recipeImages/716298-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 4,
        title: "North African Chickpea Soup",
        image: "https://spoonacular.com/recipeImages/653275-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "american",
    results: [
      {
        id: 715594,
        title: "Homemade Garlic and Basil French Fries",
        image: "https://spoonacular.com/recipeImages/715594-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715424,
        title: "The Best Chili",
        image: "https://spoonacular.com/recipeImages/715424-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642540,
        title: "Falafel Burgers",
        image: "https://spoonacular.com/recipeImages/642540-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646512,
        title: "Salmon Caesar Salad",
        image: "https://spoonacular.com/recipeImages/646512-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1046982,
        title: "How to Make the Perfect Sweet Potato Sloppy Joes",
        image: "https://spoonacular.com/recipeImages/1046982-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633837,
        title: "Baked Sweet Potato Fries",
        image: "https://spoonacular.com/recipeImages/633837-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639392,
        title: "Chunky Two-Bean Chili",
        image: "https://spoonacular.com/recipeImages/639392-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637897,
        title: "Chicken and Chickpea Chili",
        image: "https://spoonacular.com/recipeImages/637897-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638552,
        title: "Chili chops with cauliflower salad",
        image: "https://spoonacular.com/recipeImages/638552-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644581,
        title: "Ginger Garlic Chili Salmon",
        image: "https://spoonacular.com/recipeImages/644581-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 651190,
        title: "Masala-Tofu Burger",
        image: "https://spoonacular.com/recipeImages/651190-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660288,
        title: "Slow Cooker Kahlua Pork with Sweet Chili Pineapple Sauce",
        image: "https://spoonacular.com/recipeImages/660288-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 991010,
        title: "Chicken Ranch Burgers",
        image: "https://spoonacular.com/recipeImages/991010-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642695,
        title: "Feta Stuffed Burgers",
        image: "https://spoonacular.com/recipeImages/642695-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637631,
        title: "Cheesy Bacon Burger with Spicy Chipotle Aiolo Sauce",
        image: "https://spoonacular.com/recipeImages/637631-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636573,
        title: "Butternut Squash and Black Bean Chili with Bulgar",
        image: "https://spoonacular.com/recipeImages/636573-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660395,
        title: "Smokey Rainbow Chili",
        image: "https://spoonacular.com/recipeImages/660395-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 775621,
        title: "Gorgonzola & Grilled Peach Burger",
        image: "https://spoonacular.com/recipeImages/775621-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649141,
        title: "La Bella Italian Turkey Burger",
        image: "https://spoonacular.com/recipeImages/649141-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641627,
        title: "Dr Pepper Pulled Pork",
        image: "https://spoonacular.com/recipeImages/641627-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "british",
    results: [
      {
        id: 75081,
        title: "Beef Wellington",
        image: "https://spoonacular.com/recipeImages/75081-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643450,
        title: "Fresh Cherry Scones",
        image: "https://spoonacular.com/recipeImages/643450-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639637,
        title: "Classic scones",
        image: "https://spoonacular.com/recipeImages/639637-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658300,
        title: "Rich Jelly Scones",
        image: "https://spoonacular.com/recipeImages/658300-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637675,
        title: "Cheesy Potato Corn Scones",
        image: "https://spoonacular.com/recipeImages/637675-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636970,
        title: "Caramel Almond Berry Trifle",
        image: "https://spoonacular.com/recipeImages/636970-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 661725,
        title: "Strawberries and Cream Scones",
        image: "https://spoonacular.com/recipeImages/661725-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634847,
        title: "Berry and White Chocolate Trifle",
        image: "https://spoonacular.com/recipeImages/634847-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 655300,
        title: "Peanut Butter Cup Trifle",
        image: "https://spoonacular.com/recipeImages/655300-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 82518,
        title: "Tenderloin Beef Wellington",
        image: "https://spoonacular.com/recipeImages/82518-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641650,
        title: "Dried Cherry-Almond Scones",
        image: "https://spoonacular.com/recipeImages/641650-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641651,
        title: "Dried Fruit and Ginger Scones",
        image: "https://spoonacular.com/recipeImages/641651-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 659463,
        title: "Savory Cheese Dill Scones",
        image: "https://spoonacular.com/recipeImages/659463-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654657,
        title: "Parmesan Cheese Scones",
        image: "https://spoonacular.com/recipeImages/654657-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642413,
        title: "English Berry Trifle",
        image: "https://spoonacular.com/recipeImages/642413-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 59431,
        title: "Berry Trifle",
        image: "https://spoonacular.com/recipeImages/59431-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 471334,
        title: "Cheese and Corn Scones",
        image: "https://spoonacular.com/recipeImages/471334-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649853,
        title: "Lemon-Poppy Seed Scones",
        image: "https://spoonacular.com/recipeImages/649853-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 657768,
        title: "Raisin Scones",
        image: "https://spoonacular.com/recipeImages/657768-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658326,
        title: "Ricotta Chocolate Chips Scones",
        image: "https://spoonacular.com/recipeImages/658326-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "cajun",
    results: [
      {
        id: 782601,
        title: "Red Kidney Bean Jambalaya",
        image: "https://spoonacular.com/recipeImages/782601-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648524,
        title: "Jean's Seafood Gumbo",
        image: "https://spoonacular.com/recipeImages/648524-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648432,
        title: "Jambalaya Stew",
        image: "https://spoonacular.com/recipeImages/648432-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 659638,
        title: "Seafood Gumbo",
        image: "https://spoonacular.com/recipeImages/659638-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636714,
        title: "Cajun Cuisine: Vegan Jambalaya",
        image: "https://spoonacular.com/recipeImages/636714-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636732,
        title: "Cajun Lobster Pasta",
        image: "https://spoonacular.com/recipeImages/636732-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715545,
        title: "How to Make the Best Chicken Jambalaya",
        image: "https://spoonacular.com/recipeImages/715545-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636736,
        title: "Cajun Seafood and Andouille Sausage Gumbo",
        image: "https://spoonacular.com/recipeImages/636736-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1055614,
        title: "How to Make a Louisiana Style Gumbo",
        image: "https://spoonacular.com/recipeImages/1055614-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640166,
        title:
          "Cornmeal-Crusted Catfish with Cajun Seasoning and Spicy Tartar Sauce",
        image: "https://spoonacular.com/recipeImages/640166-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715384,
        title: "Louisiana Style Gumbo",
        image: "https://spoonacular.com/recipeImages/715384-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636733,
        title: "Cajun Potato Wedges",
        image: "https://spoonacular.com/recipeImages/636733-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648430,
        title: "Jambalaya Soup",
        image: "https://spoonacular.com/recipeImages/648430-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715396,
        title: "Cajun Louisiana Style Crawfish Etouffee",
        image: "https://spoonacular.com/recipeImages/715396-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660283,
        title: "SLOW COOKER CHICKEN GUMBO SOUP",
        image: "https://spoonacular.com/recipeImages/660283-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 635263,
        title: "Blackened Cajun Chicken",
        image: "https://spoonacular.com/recipeImages/635263-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636743,
        title: "Cajun Shrimp and Marinated Cucumber Salad",
        image: "https://spoonacular.com/recipeImages/636743-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 606953,
        title: "Cajun Chicken Pasta",
        image: "https://spoonacular.com/recipeImages/606953-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636742,
        title: "Cajun Shrimp Chowder",
        image: "https://spoonacular.com/recipeImages/636742-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 631882,
        title: "5-Minute Rocky Road Fudge",
        image: "https://spoonacular.com/recipeImages/631882-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "caribbean",
    results: [
      {
        id: 663822,
        title: "Trinidad Callaloo Soup",
        image: "https://spoonacular.com/recipeImages/663822-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637099,
        title: "Caribbean black bean and sweet potato soup",
        image: "https://spoonacular.com/recipeImages/637099-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637103,
        title: "Caribbean Chicken Thighs",
        image: "https://spoonacular.com/recipeImages/637103-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637116,
        title: "Caribbean Truffle Pie",
        image: "https://spoonacular.com/recipeImages/637116-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 655687,
        title: "Peppermint White Chocolate Fudge",
        image: "https://spoonacular.com/recipeImages/655687-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "chinese",
    results: [
      {
        id: 716426,
        title: "Cauliflower, Brown Rice, and Vegetable Fried Rice",
        image: "https://spoonacular.com/recipeImages/716426-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644826,
        title: "Gluten Free Dairy Free Sugar Free Chinese Chicken Salad",
        image: "https://spoonacular.com/recipeImages/644826-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716311,
        title: "Mango Fried Rice",
        image: "https://spoonacular.com/recipeImages/716311-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660231,
        title: "Skinny Veggie Fried Rice",
        image: "https://spoonacular.com/recipeImages/660231-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663150,
        title: "Thai Savory Brown Fried Rice",
        image: "https://spoonacular.com/recipeImages/663150-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638642,
        title: "Chinese Chicken Salad With Chipotle Dressing",
        image: "https://spoonacular.com/recipeImages/638642-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638649,
        title: "Chinese Chicken Salad With Creamy Soy Dressing",
        image: "https://spoonacular.com/recipeImages/638649-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638369,
        title: "Korean Sweet n Sour Chicken",
        image: "https://spoonacular.com/recipeImages/638369-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 661351,
        title: "Spinach Soup With Wontons",
        image: "https://spoonacular.com/recipeImages/661351-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663169,
        title: "Thai Veggie Slaw with Peanut Dressing and Crispy Wontons",
        image: "https://spoonacular.com/recipeImages/663169-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646425,
        title: "Healthier Pork Fried Rice",
        image: "https://spoonacular.com/recipeImages/646425-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638722,
        title: "Chinese Style Stewed Meatballs",
        image: "https://spoonacular.com/recipeImages/638722-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 656777,
        title: "Pork Fried Rice",
        image: "https://spoonacular.com/recipeImages/656777-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658270,
        title: "Rice Noodles With Wonton/chinese Ravioli In Mushroom Sauce",
        image: "https://spoonacular.com/recipeImages/658270-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642125,
        title: "Easy Thai Fried Rice",
        image: "https://spoonacular.com/recipeImages/642125-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633093,
        title: "Autumn Fried Rice with Buffalo Nuts®",
        image: "https://spoonacular.com/recipeImages/633093-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643808,
        title: "Fried Stuffed Wontons with Healthy Dark Chocolate",
        image: "https://spoonacular.com/recipeImages/643808-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660707,
        title: "Southwest Egg Rolls with Cilantro Lime Pesto",
        image: "https://spoonacular.com/recipeImages/660707-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638714,
        title: "Chinese Style Chicken and Noodle Stir Fry",
        image: "https://spoonacular.com/recipeImages/638714-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095843,
        title: "Chinese Scallion Pancakes",
        image: "https://spoonacular.com/recipeImages/1095843-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "eastern european",
    results: [
      {
        id: 715563,
        title: "Pierogi Casserole",
        image: "https://spoonacular.com/recipeImages/715563-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644476,
        title: "German Goulash",
        image: "https://spoonacular.com/recipeImages/644476-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095836,
        title: "Romanian Pea and Chicken Stew",
        image: "https://spoonacular.com/recipeImages/1095836-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633063,
        title: "Austrian Goulash",
        image: "https://spoonacular.com/recipeImages/633063-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 656049,
        title: "Pierogies with Caramelized Onion, Cabbage, and Potato",
        image: "https://spoonacular.com/recipeImages/656049-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095993,
        title: "Slow Cooker Shanghai-Style Beef Borscht",
        image: "https://spoonacular.com/recipeImages/1095993-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647645,
        title: "Hungarian Beef Goulash",
        image: "https://spoonacular.com/recipeImages/647645-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647656,
        title: "Hungarian Goulash Soup",
        image: "https://spoonacular.com/recipeImages/647656-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663792,
        title: "Transylvanian Goulash",
        image: "https://spoonacular.com/recipeImages/663792-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 635686,
        title: "Borscht Soup",
        image: "https://spoonacular.com/recipeImages/635686-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664396,
        title: "Vegan Beet Borscht",
        image: "https://spoonacular.com/recipeImages/664396-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664031,
        title: "Turkey Goulash By Mommie Cooks",
        image: "https://spoonacular.com/recipeImages/664031-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642147,
        title: "Easy Weeknight Beef Stroganoff",
        image: "https://spoonacular.com/recipeImages/642147-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647661,
        title: "Hungarian Potato Soup",
        image: "https://spoonacular.com/recipeImages/647661-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647659,
        title: "Hungarian Plum Dumplings",
        image: "https://spoonacular.com/recipeImages/647659-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 157964,
        title: "Mashed Potato and Pea Perogies",
        image: "https://spoonacular.com/recipeImages/157964-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634699,
        title: "Beef Stroganoff w Bella Mushrooms",
        image: "https://spoonacular.com/recipeImages/634699-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095839,
        title: "Pernik - Czech Spice Cake",
        image: "https://spoonacular.com/recipeImages/1095839-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647065,
        title: "Homemade Pierogies with Sauteed Onions",
        image: "https://spoonacular.com/recipeImages/647065-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 661602,
        title: "Sterling Cooper Blini with Caviar",
        image: "https://spoonacular.com/recipeImages/661602-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "european",
    results: [
      {
        id: 715769,
        title: "Broccolini Quinoa Pilaf",
        image: "https://spoonacular.com/recipeImages/715769-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715495,
        title: "Turkey Tomato Cheese Pizza",
        image: "https://spoonacular.com/recipeImages/715495-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715573,
        title: "Simple Skillet Lasagna",
        image: "https://spoonacular.com/recipeImages/715573-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 659109,
        title: "Salmon Quinoa Risotto",
        image: "https://spoonacular.com/recipeImages/659109-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648279,
        title: "Italian Tuna Pasta",
        image: "https://spoonacular.com/recipeImages/648279-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648257,
        title: "Italian Steamed Artichokes",
        image: "https://spoonacular.com/recipeImages/648257-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660266,
        title: "Slow Cooked Corned Beef and Cabbage",
        image: "https://spoonacular.com/recipeImages/660266-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648247,
        title: "Italian Seafood Stew",
        image: "https://spoonacular.com/recipeImages/648247-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640819,
        title: "Crispy Italian Cauliflower Poppers Appetizer",
        image: "https://spoonacular.com/recipeImages/640819-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095806,
        title: "Spanish style salmon fillets",
        image: "https://spoonacular.com/recipeImages/1095806-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633754,
        title: "Baked Ratatouille",
        image: "https://spoonacular.com/recipeImages/633754-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095745,
        title: "Mushroom Hummus Crostini",
        image: "https://spoonacular.com/recipeImages/1095745-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658753,
        title: "Roma Tomato Bruschetta",
        image: "https://spoonacular.com/recipeImages/658753-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664737,
        title: "Veggie Lasagna Rolls with Peppery Pecorino Marinara",
        image: "https://spoonacular.com/recipeImages/664737-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716300,
        title: "Plantain Pizza",
        image: "https://spoonacular.com/recipeImages/716300-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664565,
        title: "Vegetable Minestrone Soup",
        image: "https://spoonacular.com/recipeImages/664565-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658515,
        title: "Roasted Brussels Sprouts With Garlic",
        image: "https://spoonacular.com/recipeImages/658515-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639606,
        title: "Classic Greek Moussaka",
        image: "https://spoonacular.com/recipeImages/639606-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715563,
        title: "Pierogi Casserole",
        image: "https://spoonacular.com/recipeImages/715563-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095742,
        title: "Winter Vegetable Minestrone Soup",
        image: "https://spoonacular.com/recipeImages/1095742-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "french",
    results: [
      {
        id: 633754,
        title: "Baked Ratatouille",
        image: "https://spoonacular.com/recipeImages/633754-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640693,
        title: "Creamy Ratatouille Over Penne",
        image: "https://spoonacular.com/recipeImages/640693-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 657933,
        title: "Ratatouille Pasta",
        image: "https://spoonacular.com/recipeImages/657933-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 662291,
        title: "Sun-Dried Tomato and Leek Quiche",
        image: "https://spoonacular.com/recipeImages/662291-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658641,
        title: "Roasted Ratatouille Gratin",
        image: "https://spoonacular.com/recipeImages/658641-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640869,
        title: "Crock Pot Shredded French Dip",
        image: "https://spoonacular.com/recipeImages/640869-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647687,
        title: "Ratatouille",
        image: "https://spoonacular.com/recipeImages/647687-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 657939,
        title: "Ratatouille With Brie",
        image: "https://spoonacular.com/recipeImages/657939-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639599,
        title: "Classic French Mussels",
        image: "https://spoonacular.com/recipeImages/639599-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648641,
        title: "Julia Child's Ratatouille",
        image: "https://spoonacular.com/recipeImages/648641-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715569,
        title: "Strawberry Cheesecake Chocolate Crepes",
        image: "https://spoonacular.com/recipeImages/715569-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 652651,
        title: "Mushroom Crepes with Vegetarian Sauce",
        image: "https://spoonacular.com/recipeImages/652651-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716414,
        title: "Red, White & Blue Crepes: Happy July 4th! @driscollsberry",
        image: "https://spoonacular.com/recipeImages/716414-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664689,
        title: "Vegetarian Ratatouille",
        image: "https://spoonacular.com/recipeImages/664689-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 659037,
        title: "Salmon and Broccoli Crepes",
        image: "https://spoonacular.com/recipeImages/659037-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648638,
        title: "Julia Child's Coq au Vin",
        image: "https://spoonacular.com/recipeImages/648638-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645833,
        title: "Grilled Ratatouille",
        image: "https://spoonacular.com/recipeImages/645833-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 652652,
        title: "Mushroom Crepes",
        image: "https://spoonacular.com/recipeImages/652652-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646729,
        title: "Herbed Vegetables In A Feta Quiche With A Wild Rice Crust",
        image: "https://spoonacular.com/recipeImages/646729-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643372,
        title: "French Onion Salisbury Steak",
        image: "https://spoonacular.com/recipeImages/643372-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "german",
    results: [
      {
        id: 656817,
        title: "Pork Schnitzel And Apple Salad",
        image: "https://spoonacular.com/recipeImages/656817-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096208,
        title: "Spinach Goats Cheese Roulade Main Dish",
        image: "https://spoonacular.com/recipeImages/1096208-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649183,
        title: "Lamb and Fresh Goat Cheese Roulade",
        image: "https://spoonacular.com/recipeImages/649183-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644482,
        title: "German Meatloaf Falscher Hase",
        image: "https://spoonacular.com/recipeImages/644482-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638493,
        title: "Chicken/sweet Potato Roulade With Goat Cheese Sauce",
        image: "https://spoonacular.com/recipeImages/638493-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095834,
        title: "German Braised Red Cabbage",
        image: "https://spoonacular.com/recipeImages/1095834-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 656819,
        title: "Pork schnitzel with tarragon cream sauce",
        image: "https://spoonacular.com/recipeImages/656819-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096205,
        title: "Zucchini Feta Roulade",
        image: "https://spoonacular.com/recipeImages/1096205-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644504,
        title: "German White Chocolate Cake",
        image: "https://spoonacular.com/recipeImages/644504-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644488,
        title: "German Rhubarb Cake with Meringue",
        image: "https://spoonacular.com/recipeImages/644488-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644477,
        title: "German Lemon Cake With Cranberry Aka Cranberry Zitronenkuchen",
        image: "https://spoonacular.com/recipeImages/644477-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643851,
        title: "Frikadellen German Meat Patties",
        image: "https://spoonacular.com/recipeImages/643851-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 635108,
        title: "Black Forest Cake For Blogger Friends",
        image: "https://spoonacular.com/recipeImages/635108-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641308,
        title: "Decadent Black Forest Cake",
        image: "https://spoonacular.com/recipeImages/641308-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644462,
        title: "German Chocolate Drink with Xocai Healthy Chocolate",
        image: "https://spoonacular.com/recipeImages/644462-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "greek",
    results: [
      {
        id: 639606,
        title: "Classic Greek Moussaka",
        image: "https://spoonacular.com/recipeImages/639606-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664678,
        title: "Vegetarian Moussaka With Portabella",
        image: "https://spoonacular.com/recipeImages/664678-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645646,
        title: "Grilled Chicken Gyros With Tzatziki",
        image: "https://spoonacular.com/recipeImages/645646-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649225,
        title: "Lamb Moussaka",
        image: "https://spoonacular.com/recipeImages/649225-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649354,
        title: "Layered Greek Salad",
        image: "https://spoonacular.com/recipeImages/649354-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649195,
        title: "Lamb Burgers With Tzatziki Sauce",
        image: "https://spoonacular.com/recipeImages/649195-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660843,
        title: "Spanakopita (Greek Spinach Pie)",
        image: "https://spoonacular.com/recipeImages/660843-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 656820,
        title: "Pork Shoulder Tacos with Chipotle Greek Yogurt and Coleslaw",
        image: "https://spoonacular.com/recipeImages/656820-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096161,
        title: "Greek Chicken Sheet Pan Dinner with Green Beans and Feta",
        image: "https://spoonacular.com/recipeImages/1096161-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645348,
        title: "Greek Side Salad",
        image: "https://spoonacular.com/recipeImages/645348-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645384,
        title: "Greek Yogurt Chicken Salad",
        image: "https://spoonacular.com/recipeImages/645384-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645354,
        title: "Greek Shrimp Orzo",
        image: "https://spoonacular.com/recipeImages/645354-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1098350,
        title: "Light Greek Lemon Chicken Orzo Soup",
        image: "https://spoonacular.com/recipeImages/1098350-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642287,
        title: "Eggplant Fries with Tzatziki Sauce",
        image: "https://spoonacular.com/recipeImages/642287-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645265,
        title: "Great Greek Salad",
        image: "https://spoonacular.com/recipeImages/645265-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654939,
        title: "Pasta With Roasted Vegetables & Greek Olives",
        image: "https://spoonacular.com/recipeImages/654939-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645315,
        title: "Greek Inspired Spring Omelet",
        image: "https://spoonacular.com/recipeImages/645315-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646071,
        title: "Gyros",
        image: "https://spoonacular.com/recipeImages/646071-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095731,
        title: "Peach and Pistachio Greek Yogurt Bowl",
        image: "https://spoonacular.com/recipeImages/1095731-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716403,
        title: "Easy Lemon Feta Greek Yogurt Dip",
        image: "https://spoonacular.com/recipeImages/716403-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "indian",
    results: [
      {
        id: 798400,
        title:
          "Spicy Black-Eyed Pea Curry with Swiss Chard and Roasted Eggplant",
        image: "https://spoonacular.com/recipeImages/798400-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646043,
        title: "Gujarati Dry Mung Bean Curry",
        image: "https://spoonacular.com/recipeImages/646043-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716364,
        title: "Rice and Peas with Coconut Curry Mackerel",
        image: "https://spoonacular.com/recipeImages/716364-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660290,
        title: "Slow Cooker Lamb Curry",
        image: "https://spoonacular.com/recipeImages/660290-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641122,
        title: "Curry Leaves Potato Chips",
        image: "https://spoonacular.com/recipeImages/641122-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642468,
        title: "Ethiopian Lentil Curry",
        image: "https://spoonacular.com/recipeImages/642468-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658482,
        title: "Roasted Acorn Squash Stuffed with spicy Biryani (Veg/vegan)",
        image: "https://spoonacular.com/recipeImages/658482-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641128,
        title: "Curry Mussels",
        image: "https://spoonacular.com/recipeImages/641128-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633088,
        title: "Authentic Jamaican Curry Chicken",
        image: "https://spoonacular.com/recipeImages/633088-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641111,
        title: "Curry Beef Over Rice Noodles",
        image: "https://spoonacular.com/recipeImages/641111-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 650484,
        title: "Luscious Palak Paneer",
        image: "https://spoonacular.com/recipeImages/650484-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 652542,
        title: "Mughlai Malai Kofta Curry",
        image: "https://spoonacular.com/recipeImages/652542-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649199,
        title: "Lamb Chops Masala",
        image: "https://spoonacular.com/recipeImages/649199-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 651726,
        title: "Green Curry Chicken Salad",
        image: "https://spoonacular.com/recipeImages/651726-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641908,
        title: "Easy Chicken Tikka Masala",
        image: "https://spoonacular.com/recipeImages/641908-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637422,
        title: "Chana Masala in Minty Yogurt sauce",
        image: "https://spoonacular.com/recipeImages/637422-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637391,
        title: "Chai Pani’s Malabar Chicken Curry",
        image: "https://spoonacular.com/recipeImages/637391-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 632983,
        title: "Assam Fish Curry",
        image: "https://spoonacular.com/recipeImages/632983-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640234,
        title: "Couscous Biryani",
        image: "https://spoonacular.com/recipeImages/640234-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 661740,
        title: "Strawberry and Banana Lassi",
        image: "https://spoonacular.com/recipeImages/661740-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "irish",
    results: [
      {
        id: 660266,
        title: "Slow Cooked Corned Beef and Cabbage",
        image: "https://spoonacular.com/recipeImages/660266-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640134,
        title: "Corned Beef and Cabbage",
        image: "https://spoonacular.com/recipeImages/640134-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640136,
        title: "Corned Beef And Cabbage With Irish Mustard Sauce",
        image: "https://spoonacular.com/recipeImages/640136-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646034,
        title: "Guinness Braised Corned Beef and Cabbage",
        image: "https://spoonacular.com/recipeImages/646034-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647974,
        title: "Irish Colcannon",
        image: "https://spoonacular.com/recipeImages/647974-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664680,
        title: "Vegetarian Mushroom Shepherd's Pie",
        image: "https://spoonacular.com/recipeImages/664680-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664419,
        title: "Vegan Colcannon Soup",
        image: "https://spoonacular.com/recipeImages/664419-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649395,
        title: "Lean Shepherd's Pie",
        image: "https://spoonacular.com/recipeImages/649395-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648718,
        title: "Kale Colcannon",
        image: "https://spoonacular.com/recipeImages/648718-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634660,
        title: "Beef Pot Pies with Irish Cheddar Crust",
        image: "https://spoonacular.com/recipeImages/634660-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642091,
        title: "Easy Shepherd's Pie (Beef And/or Lamb Combo)",
        image: "https://spoonacular.com/recipeImages/642091-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636096,
        title: "Bridget Jones's Shepherd's Pie",
        image: "https://spoonacular.com/recipeImages/636096-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095888,
        title: "Irish Brown Soda Bread",
        image: "https://spoonacular.com/recipeImages/1095888-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639900,
        title: "Colcannon",
        image: "https://spoonacular.com/recipeImages/639900-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658803,
        title: "Rosemary Rum Raisin Soda Bread with Pecans",
        image: "https://spoonacular.com/recipeImages/658803-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 652760,
        title: "Mussels in Irish Ale",
        image: "https://spoonacular.com/recipeImages/652760-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648006,
        title: "Irish Soda Bread By Mommie Cooks",
        image: "https://spoonacular.com/recipeImages/648006-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 653500,
        title: "Oatmeal, Apricot, Walnut Soda Bread",
        image: "https://spoonacular.com/recipeImages/653500-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648010,
        title: "Irish Whiskey Pie",
        image: "https://spoonacular.com/recipeImages/648010-312x231.png",
        imageType: "png",
      },
      {
        id: 650602,
        title: "Madeleines With Irish Whiskey Fudge",
        image: "https://spoonacular.com/recipeImages/650602-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "italian",
    results: [
      {
        id: 715769,
        title: "Broccolini Quinoa Pilaf",
        image: "https://spoonacular.com/recipeImages/715769-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715495,
        title: "Turkey Tomato Cheese Pizza",
        image: "https://spoonacular.com/recipeImages/715495-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715573,
        title: "Simple Skillet Lasagna",
        image: "https://spoonacular.com/recipeImages/715573-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 659109,
        title: "Salmon Quinoa Risotto",
        image: "https://spoonacular.com/recipeImages/659109-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648279,
        title: "Italian Tuna Pasta",
        image: "https://spoonacular.com/recipeImages/648279-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648257,
        title: "Italian Steamed Artichokes",
        image: "https://spoonacular.com/recipeImages/648257-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648247,
        title: "Italian Seafood Stew",
        image: "https://spoonacular.com/recipeImages/648247-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640819,
        title: "Crispy Italian Cauliflower Poppers Appetizer",
        image: "https://spoonacular.com/recipeImages/640819-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095745,
        title: "Mushroom Hummus Crostini",
        image: "https://spoonacular.com/recipeImages/1095745-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658753,
        title: "Roma Tomato Bruschetta",
        image: "https://spoonacular.com/recipeImages/658753-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664737,
        title: "Veggie Lasagna Rolls with Peppery Pecorino Marinara",
        image: "https://spoonacular.com/recipeImages/664737-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716300,
        title: "Plantain Pizza",
        image: "https://spoonacular.com/recipeImages/716300-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664565,
        title: "Vegetable Minestrone Soup",
        image: "https://spoonacular.com/recipeImages/664565-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658515,
        title: "Roasted Brussels Sprouts With Garlic",
        image: "https://spoonacular.com/recipeImages/658515-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095742,
        title: "Winter Vegetable Minestrone Soup",
        image: "https://spoonacular.com/recipeImages/1095742-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715538,
        title:
          "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
        image: "https://spoonacular.com/recipeImages/715538-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642095,
        title: "Easy Skillet Garden Lasagna",
        image: "https://spoonacular.com/recipeImages/642095-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648275,
        title: "Italian Tomato and Mozzarella Caprese",
        image: "https://spoonacular.com/recipeImages/648275-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 632935,
        title: "Asparagus Lemon Risotto",
        image: "https://spoonacular.com/recipeImages/632935-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648176,
        title: "Italian Meatloaf with Hard Boiled Eggs",
        image: "https://spoonacular.com/recipeImages/648176-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "japanese",
    results: [
      {
        id: 652078,
        title: "Miso Soup With Thin Noodles",
        image: "https://spoonacular.com/recipeImages/652078-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634710,
        title: "Beef Teriyaki Stir Fry",
        image: "https://spoonacular.com/recipeImages/634710-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648506,
        title: "Japanese Sushi",
        image: "https://spoonacular.com/recipeImages/648506-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095955,
        title: "Instant Pot Pork Tenderloin Teriyaki",
        image: "https://spoonacular.com/recipeImages/1095955-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648460,
        title: "Japanese Chicken Donburi",
        image: "https://spoonacular.com/recipeImages/648460-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637908,
        title: "Chicken and Miso Ramen Noodle Soup",
        image: "https://spoonacular.com/recipeImages/637908-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633841,
        title: "Baked Teriyaki Chicken Drumsticks",
        image: "https://spoonacular.com/recipeImages/633841-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638382,
        title: "Chicken Teriyaki with Soba Noodles",
        image: "https://spoonacular.com/recipeImages/638382-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648500,
        title: "Japanese Steak Salad",
        image: "https://spoonacular.com/recipeImages/648500-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648470,
        title: "Japanese Curry Puffs",
        image: "https://spoonacular.com/recipeImages/648470-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660493,
        title: "Soba Noodle In Kombu Dashi With Teriyaki Salmon",
        image: "https://spoonacular.com/recipeImages/660493-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095743,
        title: "Coconut Curry Ramen Noodles",
        image: "https://spoonacular.com/recipeImages/1095743-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 653008,
        title: "Neoguri (Spicy Seafood Ramen)",
        image: "https://spoonacular.com/recipeImages/653008-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654072,
        title: "Oriental Filet Mignon on Crisp Kataifi with Shrimp Tempura",
        image: "https://spoonacular.com/recipeImages/654072-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663033,
        title:
          "Teriyaki Flank Steak Sandwich With Napa Cabbage, Red Bell Peppers & Carrots",
        image: "https://spoonacular.com/recipeImages/663033-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648487,
        title: "Japanese Pickles",
        image: "https://spoonacular.com/recipeImages/648487-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648462,
        title: "Japanese Clear Soup",
        image: "https://spoonacular.com/recipeImages/648462-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 653973,
        title: "Orange Teriyaki Chicken",
        image: "https://spoonacular.com/recipeImages/653973-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 646974,
        title: "Homemade Creamy Ramen Soup",
        image: "https://spoonacular.com/recipeImages/646974-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654430,
        title:
          "Pan Seared Fresh Maine Diver Scallops Creamy Avocado Champagne Grape Salad Teriyaki Cabernet Butter Sauce",
        image: "https://spoonacular.com/recipeImages/654430-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "jewish",
    results: [
      {
        id: 658125,
        title: "Red Wine Braised Beef Brisket",
        image: "https://spoonacular.com/recipeImages/658125-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634486,
        title: "BBQ Beef Brisket",
        image: "https://spoonacular.com/recipeImages/634486-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634751,
        title: "Beer Braised Brisket with Ding Dang Good Sauce",
        image: "https://spoonacular.com/recipeImages/634751-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649300,
        title:
          "Latkes; Fried Vegetable Pancakes from Europe and the Middle East",
        image: "https://spoonacular.com/recipeImages/649300-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648608,
        title: "Jojo's Potato Pancakes",
        image: "https://spoonacular.com/recipeImages/648608-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 650703,
        title: "Mama's Challah",
        image: "https://spoonacular.com/recipeImages/650703-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 653234,
        title: "Noodle Kugel with Pineapple-Gluten free, Dairy Free",
        image: "https://spoonacular.com/recipeImages/653234-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "korean",
    results: [
      {
        id: 665379,
        title: "Winter Kimchi",
        image: "https://spoonacular.com/recipeImages/665379-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637440,
        title: "Chapchae (Korean Stir-Fried Noodles)",
        image: "https://spoonacular.com/recipeImages/637440-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648910,
        title: "Kimchi",
        image: "https://spoonacular.com/recipeImages/648910-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648909,
        title: "Kim Chi - Korean Bae Chu Kim Chi",
        image: "https://spoonacular.com/recipeImages/648909-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634965,
        title: "Bibimbab (Korean Rice w Vegetables & Beef)",
        image: "https://spoonacular.com/recipeImages/634965-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649031,
        title: "Korean Bibimbab (Rice w Vegetables & Beef)",
        image: "https://spoonacular.com/recipeImages/649031-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096217,
        title: "Healthy Cabbage Soup with Spicy Kimchi",
        image: "https://spoonacular.com/recipeImages/1096217-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649030,
        title: "Korean Beef Rice Bowl",
        image: "https://spoonacular.com/recipeImages/649030-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649036,
        title: "Korean Candy Chicken",
        image: "https://spoonacular.com/recipeImages/649036-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 665680,
        title: "Zomppa's Kimchi",
        image: "https://spoonacular.com/recipeImages/665680-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641565,
        title: "Donkatsu - Korean Breaded Pork Cutlet",
        image: "https://spoonacular.com/recipeImages/641565-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 661117,
        title: "Spicy Korean Bbq Pork",
        image: "https://spoonacular.com/recipeImages/661117-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649040,
        title: "Korean Chicken Stew",
        image: "https://spoonacular.com/recipeImages/649040-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 390813,
        title: "Easy Korean Beef",
        image: "https://spoonacular.com/recipeImages/390813-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644135,
        title: "Galbi Tang (Korean Beef Short Ribs Soup)",
        image: "https://spoonacular.com/recipeImages/644135-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641208,
        title: "Dak Bulgogi - Korean BBQ Chicken",
        image: "https://spoonacular.com/recipeImages/641208-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648916,
        title: "Kimchi/Kimchee/Gimchi (Korean Fermented Spicy Cabbage)",
        image: "https://spoonacular.com/recipeImages/648916-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649062,
        title: "Korean Perilla Pesto",
        image: "https://spoonacular.com/recipeImages/649062-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649029,
        title: "Korean Bibim Naengmyun (Instant Spicy Cold Noodles)",
        image: "https://spoonacular.com/recipeImages/649029-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 662584,
        title:
          "Sweet Potato Kimchi Hash Brunch - gluten free, dairy free, vegetarian",
        image: "https://spoonacular.com/recipeImages/662584-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "latin american",
    results: [
      {
        id: 638626,
        title: "Chimichurri Skirt Steak with Grilled Asparagus",
        image: "https://spoonacular.com/recipeImages/638626-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096025,
        title: "Steak Salad with Chimichurri Sauce",
        image: "https://spoonacular.com/recipeImages/1096025-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643055,
        title: "Flank Steak With Chimichurri Sauce",
        image: "https://spoonacular.com/recipeImages/643055-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654432,
        title:
          "Pan Seared Lamb Loin With Chimichurri & Roasted Trio Squash Salad With Goat Cheese and Pinenuts",
        image: "https://spoonacular.com/recipeImages/654432-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 631912,
        title: "A Post Thanksgiving “sopa De Tortilla”",
        image: "https://spoonacular.com/recipeImages/631912-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643428,
        title: "Fresh and Simple Swai Ceviche",
        image: "https://spoonacular.com/recipeImages/643428-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637133,
        title: "Carne Asada Burritos",
        image: "https://spoonacular.com/recipeImages/637133-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 650225,
        title: "Liz's Lomo Saltado",
        image: "https://spoonacular.com/recipeImages/650225-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 632021,
        title: "Ahi Tuna Ceviche",
        image: "https://spoonacular.com/recipeImages/632021-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638619,
        title: "Chimichurri",
        image: "https://spoonacular.com/recipeImages/638619-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644907,
        title: "Gluten-Free Tres Leches Cake",
        image: "https://spoonacular.com/recipeImages/644907-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664959,
        title: "Warm Cucumber Soup (Sopa De Pepinos)",
        image: "https://spoonacular.com/recipeImages/664959-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "merditerranean",
    results: [
      {
        id: 715769,
        title: "Broccolini Quinoa Pilaf",
        image: "https://spoonacular.com/recipeImages/715769-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715495,
        title: "Turkey Tomato Cheese Pizza",
        image: "https://spoonacular.com/recipeImages/715495-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715573,
        title: "Simple Skillet Lasagna",
        image: "https://spoonacular.com/recipeImages/715573-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 659109,
        title: "Salmon Quinoa Risotto",
        image: "https://spoonacular.com/recipeImages/659109-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648279,
        title: "Italian Tuna Pasta",
        image: "https://spoonacular.com/recipeImages/648279-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648257,
        title: "Italian Steamed Artichokes",
        image: "https://spoonacular.com/recipeImages/648257-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648247,
        title: "Italian Seafood Stew",
        image: "https://spoonacular.com/recipeImages/648247-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640819,
        title: "Crispy Italian Cauliflower Poppers Appetizer",
        image: "https://spoonacular.com/recipeImages/640819-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633754,
        title: "Baked Ratatouille",
        image: "https://spoonacular.com/recipeImages/633754-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095745,
        title: "Mushroom Hummus Crostini",
        image: "https://spoonacular.com/recipeImages/1095745-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658753,
        title: "Roma Tomato Bruschetta",
        image: "https://spoonacular.com/recipeImages/658753-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664737,
        title: "Veggie Lasagna Rolls with Peppery Pecorino Marinara",
        image: "https://spoonacular.com/recipeImages/664737-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716300,
        title: "Plantain Pizza",
        image: "https://spoonacular.com/recipeImages/716300-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664565,
        title: "Vegetable Minestrone Soup",
        image: "https://spoonacular.com/recipeImages/664565-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658515,
        title: "Roasted Brussels Sprouts With Garlic",
        image: "https://spoonacular.com/recipeImages/658515-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639606,
        title: "Classic Greek Moussaka",
        image: "https://spoonacular.com/recipeImages/639606-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095742,
        title: "Winter Vegetable Minestrone Soup",
        image: "https://spoonacular.com/recipeImages/1095742-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715538,
        title:
          "What to make for dinner tonight?? Bruschetta Style Pork & Pasta",
        image: "https://spoonacular.com/recipeImages/715538-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642095,
        title: "Easy Skillet Garden Lasagna",
        image: "https://spoonacular.com/recipeImages/642095-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664678,
        title: "Vegetarian Moussaka With Portabella",
        image: "https://spoonacular.com/recipeImages/664678-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "mexican",
    results: [
      {
        id: 795751,
        title: "Chicken Fajita Stuffed Bell Pepper",
        image: "https://spoonacular.com/recipeImages/795751-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640062,
        title: "Corn Avocado Salsa",
        image: "https://spoonacular.com/recipeImages/640062-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715421,
        title: "Cheesy Chicken Enchilada Quinoa Casserole",
        image: "https://spoonacular.com/recipeImages/715421-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715543,
        title: "Homemade Guacamole",
        image: "https://spoonacular.com/recipeImages/715543-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 651977,
        title: "Mini Stuffed Mexican Bell Peppers",
        image: "https://spoonacular.com/recipeImages/651977-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715533,
        title: "Filet Mignon Soft Tacos",
        image: "https://spoonacular.com/recipeImages/715533-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 975070,
        title: "Instant Pot Chicken Taco Soup",
        image: "https://spoonacular.com/recipeImages/975070-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715391,
        title: "Slow Cooker Chicken Taco Soup",
        image: "https://spoonacular.com/recipeImages/715391-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640117,
        title:
          "Corn-Crusted Fish Tacos With Jalapeno-Lime Sauce and Spicy Black Beans",
        image: "https://spoonacular.com/recipeImages/640117-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645856,
        title: "Grilled Salmon With Cherry, Pineapple, Mango Salsa",
        image: "https://spoonacular.com/recipeImages/645856-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664501,
        title: "Vegan Taco bowls with Cilantro Lime Cauliflower Rice",
        image: "https://spoonacular.com/recipeImages/664501-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716290,
        title: "Mango Salsa",
        image: "https://spoonacular.com/recipeImages/716290-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637157,
        title: "Carolina Caviar - Black Bean Salsa",
        image: "https://spoonacular.com/recipeImages/637157-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658180,
        title: "Restaurant Style Salsa",
        image: "https://spoonacular.com/recipeImages/658180-312x231.png",
        imageType: "png",
      },
      {
        id: 659674,
        title: "Seared Pork Chops with Mango Salsa",
        image: "https://spoonacular.com/recipeImages/659674-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 157399,
        title: "Crispy-Crowned Guacamole Fish Fillets",
        image: "https://spoonacular.com/recipeImages/157399-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 643061,
        title: "Flank Steak with Herbed Salsa",
        image: "https://spoonacular.com/recipeImages/643061-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715438,
        title: "Mexican Casserole",
        image: "https://spoonacular.com/recipeImages/715438-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715567,
        title: "Beef Fajita Marinade",
        image: "https://spoonacular.com/recipeImages/715567-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 635058,
        title: "Black Bean and Peppers Taco Filling",
        image: "https://spoonacular.com/recipeImages/635058-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "middle eastern",
    results: [
      {
        id: 766453,
        title: "Hummus and Za'atar",
        image: "https://spoonacular.com/recipeImages/766453-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 716195,
        title: "Spicy Indian-Style Hummus",
        image: "https://spoonacular.com/recipeImages/716195-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649411,
        title: "Lebanese Tabouleh",
        image: "https://spoonacular.com/recipeImages/649411-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642121,
        title: "Easy Tabouleh",
        image: "https://spoonacular.com/recipeImages/642121-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649405,
        title: "Lebanese Lentil Soup",
        image: "https://spoonacular.com/recipeImages/649405-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 665378,
        title: "Winter Fattoush Salad",
        image: "https://spoonacular.com/recipeImages/665378-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647638,
        title: "Hummus Wrap With Carrots and Cucumbers",
        image: "https://spoonacular.com/recipeImages/647638-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647634,
        title: "Hummus with roasted orange peppers",
        image: "https://spoonacular.com/recipeImages/647634-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 651832,
        title: "Middle Eastern Stuffed Lentil Zatar Bread",
        image: "https://spoonacular.com/recipeImages/651832-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658573,
        title: "Roasted Eggplant Hummus",
        image: "https://spoonacular.com/recipeImages/658573-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639950,
        title: "Colorful Red Quinoa Not So Tabbouleh Salad",
        image: "https://spoonacular.com/recipeImages/639950-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 651823,
        title: "Middle Eastern Chopped Salad",
        image: "https://spoonacular.com/recipeImages/651823-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649407,
        title: "Lebanese Falafel",
        image: "https://spoonacular.com/recipeImages/649407-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642547,
        title: "Indian-Inspired Falafel Appetizer",
        image: "https://spoonacular.com/recipeImages/642547-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638316,
        title: "Chicken Shawarma Bowl",
        image: "https://spoonacular.com/recipeImages/638316-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 657686,
        title: "Quinoa Tabbouleh Salad",
        image: "https://spoonacular.com/recipeImages/657686-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647636,
        title: "Hummus With Tahini Sauce",
        image: "https://spoonacular.com/recipeImages/647636-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642539,
        title: "Falafel Burger",
        image: "https://spoonacular.com/recipeImages/642539-312x231.png",
        imageType: "png",
      },
      {
        id: 645704,
        title: "Grilled Fattoush",
        image: "https://spoonacular.com/recipeImages/645704-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642893,
        title: "Fire-Roasted Jalapeño Hummus with Turnip and Beet Chips",
        image: "https://spoonacular.com/recipeImages/642893-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "nordic",
    results: [
      {
        id: 633830,
        title: "Baked Swedish Pancake",
        image: "https://spoonacular.com/recipeImages/633830-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648565,
        title: "Jen's Swedish Meatballs",
        image: "https://spoonacular.com/recipeImages/648565-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095945,
        title: "Tuna Sandwich Savory Cake (Swedish Smörgåstårta)",
        image: "https://spoonacular.com/recipeImages/1095945-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660225,
        title: "Skillingsbollar - Norwegian Cinnamon and Sugar Rolls",
        image: "https://spoonacular.com/recipeImages/660225-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 658970,
        title: "Saffron Buns - Swedish Lussebullar",
        image: "https://spoonacular.com/recipeImages/658970-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 648980,
        title: "Knekkebrød: Norwegian Crisp Bread",
        image: "https://spoonacular.com/recipeImages/648980-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "southern",
    results: [
      {
        id: 794538,
        title: "Almond Joy Protein Shake",
        image: "https://spoonacular.com/recipeImages/794538-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660697,
        title: "Southern Fried Catfish",
        image: "https://spoonacular.com/recipeImages/660697-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633624,
        title: "Baked Fried Chicken With Cauliflower Mash",
        image: "https://spoonacular.com/recipeImages/633624-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 729531,
        title: "Roasted Lemon Pepper Pork Tenderloin with Cornbread Stuffing",
        image: "https://spoonacular.com/recipeImages/729531-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 655219,
        title: "Peanut Butter And Chocolate Oatmeal",
        image: "https://spoonacular.com/recipeImages/655219-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 633048,
        title: "Auntie Naynay’s Spicy Greens",
        image: "https://spoonacular.com/recipeImages/633048-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095798,
        title: "Collard greens with white beans and sausage",
        image: "https://spoonacular.com/recipeImages/1095798-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 718600,
        title: "Blackberry Granola Smoothie Bowl",
        image: "https://spoonacular.com/recipeImages/718600-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 511738,
        title: "Chocolate Java Protein Shake",
        image: "https://spoonacular.com/recipeImages/511738-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644791,
        title: "Gluten Free & Flour-Less Bread with Collard Greens",
        image: "https://spoonacular.com/recipeImages/644791-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636552,
        title: "Buttermilk Cornbread and Sage Stuffing",
        image: "https://spoonacular.com/recipeImages/636552-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664058,
        title: "Turkey Pot Pie With Cornbread Crust",
        image: "https://spoonacular.com/recipeImages/664058-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 647577,
        title: "How To Make Fried Chicken Without Frying",
        image: "https://spoonacular.com/recipeImages/647577-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636026,
        title: "Breakfast Biscuits and Gravy",
        image: "https://spoonacular.com/recipeImages/636026-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 715378,
        title: "Strawberry and Nutella Cobbler",
        image: "https://spoonacular.com/recipeImages/715378-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096024,
        title: "White Cheddar Grits with Veggies",
        image: "https://spoonacular.com/recipeImages/1096024-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 636574,
        title: "Buttermilk Skillet Fried Chicken",
        image: "https://spoonacular.com/recipeImages/636574-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 634318,
        title: "Barbecued Shrimp & Grits",
        image: "https://spoonacular.com/recipeImages/634318-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 13265,
        title: "Collard Greens With Bacon",
        image: "https://spoonacular.com/recipeImages/13265-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660504,
        title: "Soft Croatian corn bread - proja",
        image: "https://spoonacular.com/recipeImages/660504-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "spanish",
    results: [
      {
        id: 1095806,
        title: "Spanish style salmon fillets",
        image: "https://spoonacular.com/recipeImages/1095806-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 662294,
        title: "Sun-Dried Tomato Romesco",
        image: "https://spoonacular.com/recipeImages/662294-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 652134,
        title: "Mixed Paella",
        image: "https://spoonacular.com/recipeImages/652134-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 631747,
        title: "Dutch Oven Paella",
        image: "https://spoonacular.com/recipeImages/631747-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095841,
        title: "Spanish Gazpacho Soup",
        image: "https://spoonacular.com/recipeImages/1095841-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654327,
        title: "Paella for Four; A Wonderful Spanish Mixed Seafood Stew",
        image: "https://spoonacular.com/recipeImages/654327-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641911,
        title: "Easy Chicken, Kielbasa and Shrimp Paella",
        image: "https://spoonacular.com/recipeImages/641911-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660883,
        title: "Spanish “Ketchup” – Romesco Sauce",
        image: "https://spoonacular.com/recipeImages/660883-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 654331,
        title: "Paella Catalane With Mussels, Squid & Crevettes",
        image: "https://spoonacular.com/recipeImages/654331-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660861,
        title: 'Spanish Gazpacho Soup In The Raw With Broiled "Cheese" Toast',
        image: "https://spoonacular.com/recipeImages/660861-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 640085,
        title: "Corn Flan Side Dish",
        image: "https://spoonacular.com/recipeImages/640085-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095794,
        title: "Spanish Tortilla",
        image: "https://spoonacular.com/recipeImages/1095794-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 639557,
        title: "Clams With Spanish Sausage",
        image: "https://spoonacular.com/recipeImages/639557-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649419,
        title: "Leche Flan (Caramel Flan)",
        image: "https://spoonacular.com/recipeImages/649419-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664284,
        title:
          "Vanilla and Lime Flan By Esperanza Platas Alvarez (Planet Food Mexico)",
        image: "https://spoonacular.com/recipeImages/664284-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 653362,
        title: "Nutella frangipane empanadas",
        image: "https://spoonacular.com/recipeImages/653362-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649441,
        title: "Leek Flan",
        image: "https://spoonacular.com/recipeImages/649441-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 660868,
        title: "Spanish Meatballs In Tomato Sauce",
        image: "https://spoonacular.com/recipeImages/660868-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 638784,
        title: "Choco Coco Loco Empanada Dessert",
        image: "https://spoonacular.com/recipeImages/638784-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642559,
        title: "Fallen Chocolate Cakes With Spanish Paprika",
        image: "https://spoonacular.com/recipeImages/642559-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "thai",
    results: [
      {
        id: 663157,
        title: "Thai Street Vendor Salmon Skewers",
        image: "https://spoonacular.com/recipeImages/663157-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663126,
        title: "Thai Pasta Salad",
        image: "https://spoonacular.com/recipeImages/663126-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663166,
        title: "Thai Tofu With Bok Choy",
        image: "https://spoonacular.com/recipeImages/663166-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663113,
        title: "Thai Green Mango Salad",
        image: "https://spoonacular.com/recipeImages/663113-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645541,
        title: "Green Thai Curry with Beef",
        image: "https://spoonacular.com/recipeImages/645541-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 641671,
        title: "Drunken Noodles (Pad Kee Mao)",
        image: "https://spoonacular.com/recipeImages/641671-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663151,
        title: "Thai Shrimp",
        image: "https://spoonacular.com/recipeImages/663151-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663108,
        title: "Thai Fish Cakes",
        image: "https://spoonacular.com/recipeImages/663108-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645474,
        title: "Green Mango Salad - Thai Side Dish",
        image: "https://spoonacular.com/recipeImages/645474-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663078,
        title: 'Thai "Chicken" Wraps',
        image: "https://spoonacular.com/recipeImages/663078-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663149,
        title: "Thai Sausage Salad",
        image: "https://spoonacular.com/recipeImages/663149-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095772,
        title: "Spicy Thai Pork Lettuce Wraps",
        image: "https://spoonacular.com/recipeImages/1095772-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663087,
        title: "Thai Coconut Beetroot Soup",
        image: "https://spoonacular.com/recipeImages/663087-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 632955,
        title: "Asparagus Thai Style With Squids",
        image: "https://spoonacular.com/recipeImages/632955-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 662427,
        title: "Sweet & Spicy Thai Relish",
        image: "https://spoonacular.com/recipeImages/662427-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663121,
        title: "Thai Massaman Curry",
        image: "https://spoonacular.com/recipeImages/663121-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663156,
        title: "Thai Stir-Fry Chicken With Cashew Nuts",
        image: "https://spoonacular.com/recipeImages/663156-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 637697,
        title: "Chelley's Thai Style Chicken Satay",
        image: "https://spoonacular.com/recipeImages/637697-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 649137,
        title: "Kyuri Tsukemono",
        image: "https://spoonacular.com/recipeImages/649137-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 663100,
        title: "Thai Cucumber Salad (By Roz)",
        image: "https://spoonacular.com/recipeImages/663100-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
  {
    cuisine: "vietnamese",
    results: [
      {
        id: 716217,
        title:
          "Vietnamese Pancakes with Vegetables, Herbs and a Fragrant Dipping Sauce (Bánh Xèo)",
        image: "https://spoonacular.com/recipeImages/716217-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096250,
        title: "Pho With Zucchini Noodles",
        image: "https://spoonacular.com/recipeImages/1096250-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 642129,
        title: "Easy To Make Spring Rolls",
        image: "https://spoonacular.com/recipeImages/642129-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664830,
        title:
          "Vietnamese Beef-Noodle Soup With Asian Greens, Okay Vietnamese/japanese",
        image: "https://spoonacular.com/recipeImages/664830-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664835,
        title: "Vietnamese Noodle Salad With Tofu",
        image: "https://spoonacular.com/recipeImages/664835-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664708,
        title: "Vegetarian Spring Rolls With Garlic Lime Sauce",
        image: "https://spoonacular.com/recipeImages/664708-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1095994,
        title: "Crock Pot Chicken Pho",
        image: "https://spoonacular.com/recipeImages/1095994-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 645634,
        title: "Grilled Chicken Banh Mi",
        image: "https://spoonacular.com/recipeImages/645634-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 1096211,
        title: "The Easiest Beef Pho",
        image: "https://spoonacular.com/recipeImages/1096211-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 918033,
        title: "Chicken Spring Rolls",
        image: "https://spoonacular.com/recipeImages/918033-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664847,
        title: "Vietnamese Spring Rolls",
        image: "https://spoonacular.com/recipeImages/664847-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 644859,
        title:
          "Gluten Free Vegetarian Spring Rolls With Thai-Style Peanut Sauce",
        image: "https://spoonacular.com/recipeImages/644859-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 664828,
        title: "Vietnamese Banh Mi",
        image: "https://spoonacular.com/recipeImages/664828-312x231.jpg",
        imageType: "jpg",
      },
      {
        id: 655903,
        title: "Phyllo Dough Baked Spring Rolls",
        image: "https://spoonacular.com/recipeImages/655903-312x231.jpg",
        imageType: "jpg",
      },
    ],
  },
];